config/routes.rb
Rails.application.routes.draw do
  get 'events/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :events, only: [:index, :create]
  root 'events#index'
  post '/event_process_action', to: 'events#event_process_action', as: 'event_process_action'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery except: [:send_user_mail]
  def index
  end

  def event_process_action
    case params[:event_action]
    when 'Send user a campaign email'
      email = params[:email]
      IterableService.send_user_mail(email)
      redirect_to root_path, notice: "Campaign email sent to #{email}"
      puts "--------x-----------------"
    when 'Get user events'
      email = params[:email]
      IterableService.get_user_events(email)
      redirect_to root_path, notice: "User events retrieved for #{email}"
    else
      render plain: 'Unknown action', status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<h1 class="text-3xl font-bold underline">
  Run Campaign Event!
</h1>

<%= form_tag(event_process_action_path, method: :post, id: 'action_form', class: 'max-w-md mx-auto p-4 bg-gray-100 shadow-md rounded') do %>
  <label for="email" class="block text-gray-700 font-semibold mb-2">Email:</label>
  <%= text_field_tag :email, nil, required: true, class: 'w-full px-4 py-2 border rounded focus:outline-none focus:border-blue-500' %>
  <small class="text-red-500">Please enter a valid email address.</small>

  <label for="event_action" class="block text-gray-700 font-semibold mt-4 mb-2">Choose an action:</label>
  <%= select_tag :event_action, options_for_select(['Send user a campaign email', 'Get user events']), class: 'w-full px-4 py-2 border rounded focus:outline-none focus:border-blue-500' %>

  <%= submit_tag 'Submit', disabled: true, id: 'submit_button', class: 'mt-4 px-4 py-2 bg-blue-500 text-white rounded cursor-pointer hover:bg-blue-600 focus:outline-none focus:shadow-outline-blue active:bg-blue-800 disabled:bg-gray-300 disabled:cursor-not-allowed' %>
<% end %>

<script>
  $(document).ready(function() {
    var form = $('#action_form');
    var actionSelect = $('#event_action');
    var submitButton = $('#submit_button');
    var emailInput = $('#email');

    emailInput.on('input', function() {
      submitButton.prop('disabled', !$(this).val().trim());
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_header.html.erb
<!-- _navbar.html.erb -->
<nav class="bg-blue-500 p-4">
  <div class="container mx-auto flex justify-between items-center">
    <!-- Left Side: Logo -->
    <div>
      <a href="/" class="text-white text-lg font-bold">
        <i class="fa fa-coffee"></i> Event Api
      </a>
    </div>

    <!-- Right Side: Sign Up/Login or Logout -->
    <div class="flex items-center">
      <% if user_signed_in? %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "bg-white text-blue-500 px-4 py-2 rounded-full" %>
      <% else %>
        <%= button_to "Sign Up", new_user_registration_path, class: "bg-white text-blue-500 px-4 py-2 rounded-full mr-2" %>
        <%= button_to "Login", new_user_session_path, class: "bg-white text-blue-500 px-4 py-2 rounded-full" %>
      <% end %>
    </div>
  </div>
</nav>